apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tags.datadoghq.com/env: dev  # Add here for unified service tagging
    tags.datadoghq.com/service: adservice # Add here for unified service tagging
    tags.datadoghq.com/version: 1.0.0 # Add here for unified service tagging
  name: adservice
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: adservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        admission.datadoghq.com/java-lib.version: v1.21.0 # Add here for APM lib injection
        ad.datadoghq.com/server.logs: >-
          [{
            "source": "java",
            "service": "adservice",
            "log_processing_rules": [{
              "type": "multi_line",
              "name": "log_start_with_date",
              "pattern" : "\\d{2}-\\d{2}-\\d{4}\\s\\d{2}:\\d{2}:\\d{2}.\\d{3}"
            }]
          }]  # Add this to identify the correct log source for ootb log pipelines for logs pattern like 31-08-2023 18:18:22.363
      labels:
        admission.datadoghq.com/enabled: "true" # Add here for APM lib injection
        app: adservice
        tags.datadoghq.com/env: dev   # Add here for unified service tagging
        tags.datadoghq.com/service: adservice    # Add here for unified service tagging
        tags.datadoghq.com/version: 1.0.0    # Add here for unified service tagging
    spec:
      containers:
      - env:
        - name: PORT
          value: "9555"
        - name: DD_LOGS_INJECTION
          value: "true"          
        image: docker.io/smazzone/adservice:a759553da31c4093c95a54403554188ec2ac229765d6c14405bbc18bce9825ae
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 9555
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 180Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 5